# Generated by Django 4.0.5 on 2023-07-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoredAPIApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='type',
            new_name='activity_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='activity_type',
            new_name='user_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='activities',
            field=models.ManyToManyField(to='BoredAPIApp.activity'),
        ),
    ]
