# Generated by Django 4.0.5 on 2023-07-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoredAPIApp', '0002_rename_type_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='activity',
            name='key',
            field=models.CharField(default='some_default_value', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('education', 'Education'), ('recreational', 'Recreational'), ('social', 'Social'), ('diy', 'DIY'), ('charity', 'Charity'), ('cooking', 'Cooking'), ('relaxation', 'Relaxation'), ('music', 'Music'), ('busywork', 'Busywork')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
