# Generated by Django 4.0.5 on 2023-07-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoredAPIApp', '0004_remove_activity_key_remove_activity_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='registration_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='activity_type',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
